### ISSUE TITLE
Failed to retrieve the document that contains the Task Object with id

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-task#132]
During a Confluence migration, a user is seeing a lot of these issues:

```
Failed to retrieve the document that contains the Task Object with id [{}]: ERROR: duplicate key value violates unique constraint "xwikidoc_pkey"
Detail: Key (xwd_id)\\u003d(-4458494136633945569) already exists.
```

(with varying ids)

Unfortunately, I haven't managed to reproduce the issue yet. I don't have a stack trace because of #131

**Comment by trrenty** [comment]
This was caused by the following piece of code: https://github.com/xwikisas/application-task/blob/6f3b57a2978419fd7728c0deff5c37e548089a60/application-task-default/src/main/java/com/xwiki/task/internal/TaskMacroUpdateEventListener.java#L141-L150 

The code was added as part of this optimization issue https://github.com/xwikisas/application-task/issues/114 . Migrating a document with multiple versions, each version containing task macros, would slow down the migration significantly. This was because each version of the document would be processed by the task listeners. The proposed solution tried to detect when the context is a migration and only process the last revision of a document. This was done by making the listener stateful which causes problems in concurrent environments.

For now, I fixed the issue partially. It can still reproduce if the Admin configures multiple "notSkippedFoldEvents" in the administration section of the Task App AND runs multiple processes that trigger the aforementioned fold events at the same time. I created another issue for that https://github.com/xwikisas/application-task/issues/160 . A solution that would fix that as well is more complicated and requires more time.
