### ISSUE TITLE
Change the Task location under a Task Manager page

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-task#63]
There is a current case when importing spaces containing tasks when they are imported as child pages of a parent page. When they are numerous, the navigation panel or page hierarchy can become too large, not very user friendly.

The suggestion would be to combine tasks over under a Task Manager page rather than as the current behaviour.

**Comment by DarkJoney** [comment]
I would like to say this is a critical flaw, we have stopped all migration processes due to this. Big spaces are wrecked, and navigation does not basically not exist in this form. And I have to find a way how to clean it up myself, because we imported 4GB of space which is a very slow process, and a few huge ones are remaining. 
 
 Weren't you referring to the confluence during the programming?  
 
 Please combine it under the top-level tree at least for now not to affect actual page navigation.  I wish to put the screenshot here, but this is my private github account.

**Comment by snazare** [comment]
We will add a configuration that will allow the Administrator to choose the location of the task pages created (under the parent page, as it is now, OR under the common main TaskManager page)

**Comment by DarkJoney** [comment]
@snazare If it would have been under the parent page like you have done with the draw.io it wouldn't be a problem at all. The current behavior is to generate HUNDRED of tasks and slap them to the root of the space making all the navigation unusable. The second option also is not optimal in my opinion. I thought it would be something like SPACE -> TaskManager -> Tasks. If you will put them under the main space, then how are you going to separate them? 

Anyway, I just want to have an answer to my colleague that asks about the task lists everyday.
